#!/usr/bin/env python3
"""Write sitemap.xml from the pages the site actually serves.

    python3 tools/build-sitemap.py
    python3 tools/build-sitemap.py --check    # exit 1 if a rebuild is pending

Two things this exists to get right, both of which are easy to get wrong by
hand and impossible to notice once wrong.

**The URLs have no `.html`.** Cloudflare Pages answers `/method.html` with a
308 to `/method`, so `/method` is the URL the site serves and `/method.html`
is a redirect to it. A sitemap full of redirecting URLs is a sitemap Search
Console reports as one long list of `Page with redirect`. The internal links
in the markup are still written `method.html`, which is fine: a 308 is
followed and consolidated. It is the canonical tag and the sitemap that
decide which URL is indexed, and both of those say the extensionless one.

**`lastmod` comes from git, not from a hand-typed date.** Freshness is one of
the few things that reliably predicts whether an answer engine cites a page,
and a `lastmod` that says today on a page last touched in July is a signal
that gets discounted once and then ignored. The date here is the last commit
that touched the file, so it is either true or the file is uncommitted, and an
uncommitted file falls back to its mtime.

Not listed, on purpose:

    next-steps.html   carries `noindex`; it is the page after the booking
    lp/, iblp/        generated ad landing pages, `noindex`, and they
                      duplicate index.html below the hero
    case-studies/     linked only from the archived student-stories section
"""

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
ORIGIN = "https://blueoceanedu.com"
OUT = ROOT / "sitemap.xml"

# file, URL path, priority. Order is the order they appear in the file, which
# is nothing but a courtesy to whoever reads it; crawlers do not read order as
# rank. `priority` and `changefreq` are advisory and Google says it ignores
# both. They are here because Bing and several of the AI crawlers do not.
PAGES = [
    ("index.html",   "/",         "1.0",  "weekly"),
    ("method.html",  "/method",   "0.9",  "monthly"),
    ("results.html", "/results",  "0.9",  "monthly"),
    ("founder.html", "/founder",  "0.9",  "monthly"),
    ("fit.html",     "/fit",      "0.8",  "monthly"),
    ("team.html",    "/team",     "0.8",  "monthly"),
    ("start.html",   "/start",    "0.7",  "monthly"),
    ("privacy.html", "/privacy",  "0.3",  "yearly"),
]


def last_modified(path):
    """Date of the last commit that touched the file, else its mtime."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        if out:
            return out
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    mtime = (ROOT / path).stat().st_mtime
    return datetime.fromtimestamp(mtime, timezone.utc).strftime("%Y-%m-%d")


def render():
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by tools/build-sitemap.py. Do not hand-edit: the next',
        '     run overwrites it. Add a page to the PAGES list in that file. -->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for filename, path, priority, changefreq in PAGES:
        source = ROOT / filename
        if not source.is_file():
            sys.exit("build-sitemap: %s is in PAGES but not on disk" % filename)
        lines += [
            "  <url>",
            "    <loc>%s</loc>" % escape(ORIGIN + path),
            "    <lastmod>%s</lastmod>" % last_modified(filename),
            "    <changefreq>%s</changefreq>" % changefreq,
            "    <priority>%s</priority>" % priority,
            "  </url>",
        ]
    lines += ["</urlset>", ""]
    return "\n".join(lines)


def main():
    xml = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.is_file() else ""
        if current != xml:
            sys.exit("build-sitemap: sitemap.xml is out of date, run "
                     "`python3 tools/build-sitemap.py`")
        print("build-sitemap: sitemap.xml is current")
        return
    OUT.write_text(xml)
    print("build-sitemap: wrote sitemap.xml, %d URLs" % len(PAGES))


if __name__ == "__main__":
    main()
