#!/usr/bin/env python3
"""Write the visible FAQ on fit.html from the same list the schema uses.

    python3 tools/build-faq.py
    python3 tools/build-faq.py --check    # exit 1 if a rebuild is pending

The question and answer pairs live in `tools/build-seo.py` as `FAQ`, because
that file also builds the `FAQPage` node that describes them. Generating both
from one list is not tidiness. Google's structured data policy is that the
answer in the markup and the answer in the schema have to match, and an FAQ
kept in two places diverges the first time somebody improves one sentence.
This is the same argument the landing-page builder makes about the hero.

The markup goes between `<!-- @faq -->` and `<!-- /@faq -->` on fit.html.
Everything else on that page is hand-written and stays that way.

Why `<details>` and not a scripted accordion: it is findable with the
browser's own page search whether or not it is open, it survives JavaScript
failing, and a crawler reads a closed answer exactly as it reads an open one.
"""

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "fit.html"
OPEN = "<!-- @faq -->"
CLOSE = "<!-- /@faq -->"


def load_faq():
    """Import FAQ out of tools/build-seo.py, whose name is not an identifier."""
    spec = importlib.util.spec_from_file_location(
        "build_seo", Path(__file__).resolve().parent / "build-seo.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.FAQ


def esc(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render(faq):
    lines = [
        OPEN,
        "      <!-- Generated by tools/build-faq.py from the FAQ list in",
        "           tools/build-seo.py, which also builds the FAQPage schema in",
        "           this page's head. Do not hand-edit: the next run overwrites",
        "           everything between these two sentinels. -->",
        '      <div class="faq-list reveal">',
    ]
    for i, (question, answer) in enumerate(faq):
        # Only the first ships open. A block of ten closed rows reads as a
        # help centre; one open row shows what kind of answer is under the
        # rest of them.
        attr = ' open' if i == 0 else ''
        lines += [
            '        <details class="faq-item"%s>' % attr,
            '          <summary class="faq-q">%s</summary>' % esc(question),
            '          <p class="faq-a">%s</p>' % esc(answer),
            "        </details>",
        ]
    lines += ["      </div>", "      " + CLOSE]
    return "\n".join(("      " + lines[0]) if i == 0 else ln
                     for i, ln in enumerate(lines))


def main():
    faq = load_faq()
    html = TARGET.read_text()
    if OPEN not in html or CLOSE not in html:
        sys.exit("build-faq: fit.html has no @faq sentinels. Add an empty\n"
                 "  <!-- @faq -->\n  <!-- /@faq -->\n"
                 "pair inside the section that should carry the FAQ, then "
                 "re-run.")
    block = render(faq).strip()
    out = re.sub(re.escape(OPEN) + r".*?" + re.escape(CLOSE),
                 lambda m: block, html, count=1, flags=re.S)

    if "--check" in sys.argv:
        if out != html:
            sys.exit("build-faq: fit.html is out of date, run "
                     "`python3 tools/build-faq.py`")
        print("build-faq: fit.html is current")
        return
    if out == html:
        print("build-faq: fit.html is already current")
        return
    TARGET.write_text(out)
    print("build-faq: wrote %d questions into fit.html" % len(faq))


if __name__ == "__main__":
    main()
